version: '3'

services:
  postgresql:
    image: "postgres:9.6-alpine"
    container_name: postgresql
    ports:
      - 5432:5432

    environment:
      - DB_SERVER=postgresql
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  project:
    build: ./
    container_name: project
    ports:
      - 8081:8081
    links:
      - postgresql